server:
  port: 8081

spring:
  config:
    import: optional:file:.env[.properties]

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          github:
            client-id: ${OAUTH_GITHUB_CLIENT_ID}
            client-secret: ${OAUTH_GITHUB_CLIENT_SECRET}
            scope:
              - user:email
              - read:user

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_GMAIL}
    password: ${MAIL_APP_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  datasource:
    url: ${POSTGRES_REGISTRATION_DOCKER_URL:jdbc:postgresql://localhost:5432/registration_db}
    password: 1234
    username: user
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      leak-detection-threshold: 300000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_updates: true
        order_inserts: true
    show-sql: false
    open-in-view: false

  data:
    redis:
      host: ${REDIS_DOCKER_HOST:localhost}
      port: 6379
      timeout: 500ms

  kafka:
    bootstrap-servers: ${KAFKA_DOCKER_URL:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true

jasypt:
  encryptor:
    password: ${JASYPT_KEY}
    provider-name: SunJCE
    algorithm: ${JASYPT_ALGORITHM}
    key-obtention-iterations: 1000
    pool-size: 1
    string-output-type: base64
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator


minio:
  url: ${MINIO_DOCKER_URL}
  bucket: user-sessions
  user: user
  password: 1234

jwt:
  private-key-base64:${JWT_PRIVATE_KEY}
  public-key-base64:${JWT_PUBLIC_KEY}